class Samsung{
public static void main(String[]args)
{
String bloodGroup="A+";
System.out.println(bloodGroup);
String animal="tiger";
System.out.println(animal);
String flower="rose";
System.out.println(flower);
String vegetable="brinjal";
System.out.println(vegetable);
String color="black";
System.out.println(color);
String fruit="mango";
System.out.println(fruit);
String milk ="badam shake";
System.out.println(milk);
String instagram="insta@1234";
System.out.println(instagram);
String chatGpt="chat@123";
System.out.println(chatGpt);
String whatsapp ="@soh0089";
System.out.println(whatsapp);
String facebook="FB@4567";
System.out.println(facebook);
String epic ="@epic1234";
System.out.println(epic);
String meesho="what_@3457";
System.out.println(meesho);
String linkedin ="linked_in@789";
System.out.println(linkedin);
String github="github@654";
System.out.println(github);
String snapchat ="@snap_4321";
System.out.println(snapchat);
String myntra ="myntra@8088";
System.out.println(myntra);
String name="sohita.patil";
System.out.println(name);
String graduation="I have completed my Btech graduation";
System.out.println(graduation);
String address="plot no.10,biddapur colony ,kalaburagi,585-103";
System.out.println(address);
String university="SB university is one of the good college in kalaburagi";
System.out.println(university);
String hospital="ESI is one of the best hospital for medication";
System.out.println(university);
String recipe="I love Masaladosa";
System.out.println(recipe);
String hobby="I like to cook the food";
System.out.println(hobby);
String internship="I have done my internship on webdevelopment";
System.out.println(internship);
String project="an IoT based smart mirror with Arduino";
System.out.println(project);
String trafficSignal="there are 3 kinds of signals";
System.out.println(trafficSignal);
String smartPhone="we can access the information through internet";
System.out.println(smartPhone);
String isckontemple="isckontemplekon is the workship place of radhe and krishna";
System.out.println(isckontemple);
String unity="unity is an IT company located in Hyderabad";
System.out.println(unity);
String banglore="banglore is known to as silicon city";
System.out.println(banglore);
String jaipur="it is known to be as pink city";
System.out.println(jaipur);
String topSize="S";
System.out.println(topSize);
String pinCode="585103";
System.out.println(pinCode);
String shoesize="6";
System.out.println(shoesize);
String mobileModel="Redmi12 5g";
System.out.println(mobileModel);
String tags="#trendingReels,#helloWorld,#armanMallikSongs";
System.out.println(tags);
String operatingSystem="windows 10";
System.out.println(operatingSystem);
String piValue="3.147";
System.out.println(piValue);
String panner="4.89kg";
System.out.println(panner);
String petrolprice="98 rupee per liter";
System.out.println(petrolprice);
String contactNo="9972997179";
System.out.println(contactNo);
String radius="radius of the earth is 6,371km";
System.out.println(radius);
String gravitation="acceleration due to gravity is 9.8ms^2";
System.out.println(gravitation);
String primeMinister="since from 3 elections Narendra modi won the Seat";
System.out.println(primeMinister);
String laptop="i'll use JDk8.0 version";
System.out.println(laptop);
String ram="8 Gb RAM";
System.out.println(ram);
String sslcPercentage="79.04%";
System.out.println(sslcPercentage);
String ambanisNetworth="$113.7 billion as of march 2024";
System.out.println(ambanisNetworth);
String humanHeartWeight="284.7g";
System.out.println(humanHeartWeight);
String greeting="hello!";
System.out.println(greeting);
String question="how are you?";
System.out.println(question);
String gmail="sohitaxworkz@gmail.com";
System.out.println(gmail);
String todaysDate="28-6-2024";
System.out.println(todaysDate);
String currentTime="15:26:02";
System.out.println(currentTime);
String distance="67kms";
System.out.println(distance);
String complexity="O(log n)";
System.out.println(complexity);
String file="notepad++";
System.out.println("file");
String array="[1,2,3,4,5,6,7,8,9]";
System.out.println("array");
String calculator="'+','-','*','/'";
System.out.println("calculator");
String hallticketNo="126293";
System.out.println("hallticketNo");
String bikeNo="KA 32 9977";
System.out.println("bikeNo");
String multiplication="56*98";
System.out.println("multiplication");
String softwareCompany="Udemy_Business";
System.out.println("softwareCompany");
String programming="java,c++,python";
System.out.println(programming);
String language="english,kannada,hindi";
System.out.println(language);
String integration="{dy/dx}";
System.out.println(integration);
String pythagorasTheorem="ac^2=ab^2+bc^2";
System.out.println(pythagorasTheorem);
String matrix="consists of rows and columns";
System.out.println(matrix);
String speed="25km/hr";
System.out.println(speed);
String factory="large no of factories are their in india";
System.out.println(factory);
String referenceVariable="it points to the location of the address";
System.out.println(referenceVariable);
String palmOil="1.45liter";
System.out.println(palmOil);
String battery="5.7volt";
System.out.println(battery);
}
}